name: Build DeepState Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up dependencies
    - name: Install required dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          g++ \
          make \
          git \
          clang \
          libc6-dev \
          libstdc++-10-dev \
          libcurl4-openssl-dev \
          zlib1g-dev \
          build-essential

    # Step 3: Clone DeepState repository
    - name: Clone DeepState repository
      run: |
        git clone --recursive https://github.com/trailofbits/deepstate.git
        cd deepstate
        mkdir build
        cd build

    # Step 4: Build DeepState
    - name: Build DeepState
      run: |
        cmake ..
        make clean
        make

    # Step 5: Run tests (optional, if needed)
    - name: Run DeepState tests
      run: |
        cd ..
        ./tests/deepstate_test
